import { HUB01_NODE_EXPERIENCE } from "./hub/hub01ShatteredFrontispiece.js";
import { HUB02_NODE_EXPERIENCE } from "./hub/hub02CompassOfGenres.js";
import { HUB03_NODE_EXPERIENCE } from "./hub/hub03MarginalIndex.js";
import { HUB04_NODE_EXPERIENCE } from "./hub/hub04ObservatoryCalibration.js";
import { HUB05_NODE_EXPERIENCE } from "./hub/hub05FirstCrossroad.js";
import { HUB06_NODE_EXPERIENCE } from "./hub/hub06CorrespondenceUnlock.js";
import { HUB07_NODE_EXPERIENCE } from "./hub/hub07TornDedication.js";
import { HUB08_NODE_EXPERIENCE } from "./hub/hub08FogKeyLattice.js";
import { CRD01_NODE_EXPERIENCE } from "./cradle/crd01PathSeeding.js";
import { CRD02_NODE_EXPERIENCE } from "./cradle/crd02MadraWell.js";
import { CRD03_NODE_EXPERIENCE } from "./cradle/crd03AuraAlignment.js";
import { CRD04_NODE_EXPERIENCE } from "./cradle/crd04SevenYearFestival.js";
import { LOG01_NODE_EXPERIENCE } from "./math/log01TruthGates.js";
import { LOG02_NODE_EXPERIENCE } from "./math/log02WitnessGrid.js";
import {
  ALG01_NODE_EXPERIENCE,
  ALG02_NODE_EXPERIENCE,
  ALG03_NODE_EXPERIENCE,
  ALG04_NODE_EXPERIENCE,
  ALG05_NODE_EXPERIENCE,
  ALG06_NODE_EXPERIENCE,
  GEO01_NODE_EXPERIENCE,
  GEO02_NODE_EXPERIENCE,
  GEO03_NODE_EXPERIENCE,
  GEO04_NODE_EXPERIENCE,
  GEO05_NODE_EXPERIENCE,
  GEO06_NODE_EXPERIENCE,
  LOG03_NODE_EXPERIENCE,
  LOG04_NODE_EXPERIENCE,
  LOG05_NODE_EXPERIENCE,
  LOG06_NODE_EXPERIENCE,
  NUM03_NODE_EXPERIENCE,
  NUM04_NODE_EXPERIENCE,
  NUM05_NODE_EXPERIENCE,
  NUM06_NODE_EXPERIENCE,
} from "./math/advancedMathNodes.js";
import { MOL01_NODE_EXPERIENCE } from "./motheroflearning/mol01MemorySpiral.js";
import { MOL02_NODE_EXPERIENCE } from "./motheroflearning/mol02LoopReset.js";
import { MOL03_NODE_EXPERIENCE } from "./motheroflearning/mol03PrestigeLattice.js";
import { NUM01_NODE_EXPERIENCE } from "./math/num01ResidueClock.js";
import { NUM02_NODE_EXPERIENCE } from "./math/num02PrimeLocks.js";
import { TWI01_NODE_EXPERIENCE } from "./wanderinginn/twi01GuestLedger.js";
import { TWI02_NODE_EXPERIENCE } from "./wanderinginn/twi02IzrilAtlas.js";
import { TWI03_NODE_EXPERIENCE } from "./wanderinginn/twi03Inn.js";
import { TWI04_NODE_EXPERIENCE } from "./wanderinginn/twi04ConstructionYard.js";
import { AA01_NODE_EXPERIENCE } from "./arcane/aa01SerpentJudgment.js";
import { AA02_NODE_EXPERIENCE } from "./arcane/aa02ClimbersCourt.js";
import { AA03_NODE_EXPERIENCE } from "./arcane/aa03Workshop.js";
import { WORM01_NODE_EXPERIENCE } from "./worm/worm01DeckDuel.js";
import { WORM02_NODE_EXPERIENCE } from "./worm/worm02Arena.js";
import { DCC01_NODE_EXPERIENCE } from "./dungeoncrawlercarl/dcc01CrawlFloor.js";
import {
  PGE01_NODE_EXPERIENCE,
  PGE02_NODE_EXPERIENCE,
  PGE03_NODE_EXPERIENCE,
  PGE04_NODE_EXPERIENCE,
  PGE05_NODE_EXPERIENCE,
  PGE06_NODE_EXPERIENCE,
} from "./practicalguide/pgeTextAdventures.js";

const NODE_EXPERIENCE_REGISTRY = Object.freeze({
  HUB01: HUB01_NODE_EXPERIENCE,
  HUB02: HUB02_NODE_EXPERIENCE,
  HUB03: HUB03_NODE_EXPERIENCE,
  HUB04: HUB04_NODE_EXPERIENCE,
  HUB05: HUB05_NODE_EXPERIENCE,
  HUB06: HUB06_NODE_EXPERIENCE,
  HUB07: HUB07_NODE_EXPERIENCE,
  HUB08: HUB08_NODE_EXPERIENCE,
  CRD01: CRD01_NODE_EXPERIENCE,
  CRD02: CRD02_NODE_EXPERIENCE,
  CRD03: CRD03_NODE_EXPERIENCE,
  CRD04: CRD04_NODE_EXPERIENCE,
  LOG01: LOG01_NODE_EXPERIENCE,
  LOG02: LOG02_NODE_EXPERIENCE,
  LOG03: LOG03_NODE_EXPERIENCE,
  LOG04: LOG04_NODE_EXPERIENCE,
  LOG05: LOG05_NODE_EXPERIENCE,
  LOG06: LOG06_NODE_EXPERIENCE,
  MOL01: MOL01_NODE_EXPERIENCE,
  MOL02: MOL02_NODE_EXPERIENCE,
  MOL03: MOL03_NODE_EXPERIENCE,
  NUM01: NUM01_NODE_EXPERIENCE,
  NUM02: NUM02_NODE_EXPERIENCE,
  NUM03: NUM03_NODE_EXPERIENCE,
  NUM04: NUM04_NODE_EXPERIENCE,
  NUM05: NUM05_NODE_EXPERIENCE,
  NUM06: NUM06_NODE_EXPERIENCE,
  ALG01: ALG01_NODE_EXPERIENCE,
  ALG02: ALG02_NODE_EXPERIENCE,
  ALG03: ALG03_NODE_EXPERIENCE,
  ALG04: ALG04_NODE_EXPERIENCE,
  ALG05: ALG05_NODE_EXPERIENCE,
  ALG06: ALG06_NODE_EXPERIENCE,
  GEO01: GEO01_NODE_EXPERIENCE,
  GEO02: GEO02_NODE_EXPERIENCE,
  GEO03: GEO03_NODE_EXPERIENCE,
  GEO04: GEO04_NODE_EXPERIENCE,
  GEO05: GEO05_NODE_EXPERIENCE,
  GEO06: GEO06_NODE_EXPERIENCE,
  TWI01: TWI01_NODE_EXPERIENCE,
  TWI02: TWI02_NODE_EXPERIENCE,
  TWI03: TWI03_NODE_EXPERIENCE,
  TWI04: TWI04_NODE_EXPERIENCE,
  AA01: AA01_NODE_EXPERIENCE,
  AA02: AA02_NODE_EXPERIENCE,
  AA03: AA03_NODE_EXPERIENCE,
  WORM01: WORM01_NODE_EXPERIENCE,
  WORM02: WORM02_NODE_EXPERIENCE,
  DCC01: DCC01_NODE_EXPERIENCE,
  PGE01: PGE01_NODE_EXPERIENCE,
  PGE02: PGE02_NODE_EXPERIENCE,
  PGE03: PGE03_NODE_EXPERIENCE,
  PGE04: PGE04_NODE_EXPERIENCE,
  PGE05: PGE05_NODE_EXPERIENCE,
  PGE06: PGE06_NODE_EXPERIENCE,
});

export function getNodeExperience(nodeId) {
  return NODE_EXPERIENCE_REGISTRY[nodeId] || null;
}
